language: node_js
matrix:
  include:
  - node_js: '8'
script:
- yarn run saucelabs
notifications:
  email: false
env:
  global:
  - secure: aegseJZEjOr3/kFOOMPq/k3VpqyU81yE6kIdXZ86nP1WejsSGr6rrv8mEMTFPPMepVSZlffMQomAo8/VVsqpX9uLT88woE5l0VIsgQXHP7n8xmnScp5FHe7LhtqdjtgvKcVsvNuTUPWd2FcsaUj0Nd7QeO9Ki3P0cedJZvVuaKYqUb5OQW4L1QYXjr/eVQQ+qRU1UY27uA2ibq2vjLCSsMCWJr/aek+GTNCrQwD30GfPvKwMfemoqGhNmwD2hTNXUff8g6pfY7N5Vj6Q95Wz3Em6rVU5a0E0yoauinYqG/ZuqPY4mQVHTxa+n3h/g0hpKyda619PNXWVFfF6gh+j4jRvGsq5fVPDtJiignaaeChB1FnxrbQ5cM1B83A9iSeS8WkuHOxnS3Ftv9PIxRQEbkCg4DAMTNu8VVw2lVRhO+zugk/s1pfw5/20AukN4xrxjCA7CRKgok2OP0S25lphIZGctAeZCCfxM3v0J/9ix6mtyiBYBp2lEG6bdN6f1A5HlTn+V8kqiiQT2iYQZKQYp0dzTiytFXC5OTaAae8Yk3EoATTiW1WkGDfd8JC+lzit4ttxBfI0WnyFxbawY7USXYrgL4y8sy7fjXneeGRw8kknzfMYcfq2DDj47HAQwGhIU1W+Tun4Op9w2UpsXSF8BDy714FsKyk0boO3qOceOYc=
  - secure: OvsZaNT/yc1IWD15092Q+iRuEy8RASV2V9t1qCTxKifY8uAvj15GOugpPYVyR2wVQ5cIMz0S6+c4tYYrHdtrJ6rQGlJV96FY8y/Q4F6MFr1aJIHcww9d9ZwkV4UHJ6mVialaQIXgBsDIlRDmthudAdEz6AwpGfx0Y5q/WzFcmIWM27rSCTMSZIgwp/dr7prOPzZZwhXOwkUFLkCpTUEDJW3Kx7ZgfB4GA+WyU2rGz9uN4gINBLmz4fiVgceu1+Br0DBHslpXwh7XvpqUO1dsgZMO/z31O6h7l25uBNjKNVJR3L6KvRrnme3fiw80ReFcrJJB2WSVJ0RgvODyEOm0FP4R1Yzh/fRuUJu6d0Nm/LYaANxCIeNTLfHTL4RQc5cSt1naTpmIM+aeYzrrlImkj4wyL+3WW+MuNU5MRO/XnCgrzE6Hyaalyu2LnCLkmmMpu0wPbZmLjXAN/kcZy7h3gf4D6OgF0KixCQyLyK1mGyI2Cqe73+Np5OotDwiQchByrCuK4nCsakynPJzeZsknfr31irDhYahc6f7BSRiZmEM/jWRs+XJ5GRq7f+WHVadjDYnZx8cVM2le67LQo+KFz0aiEUeNLBIXzEdw0w/sarkCIFjFPaaQWDFpzXrT+U1pJigW/9nKZ3RciDAEztVPWI9bR933Pr+PMgMcFLLkQEI=
